"""initial

Revision ID: 0d6be5fc027e
Revises: 
Create Date: 2024-03-28 14:41:27.643943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6be5fc027e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("create schema main")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_product_id'), 'product', ['id'], unique=False, schema='main')
    op.create_index(op.f('ix_main_product_name'), 'product', ['name'], unique=True, schema='main')
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_user_id'), 'user', ['id'], unique=False, schema='main')
    op.create_index(op.f('ix_main_user_name'), 'user', ['name'], unique=True, schema='main')
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['main.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_order_id'), 'order', ['id'], unique=False, schema='main')
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['main.order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['main.product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id'),
    schema='main'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product', schema='main')
    op.drop_index(op.f('ix_main_order_id'), table_name='order', schema='main')
    op.drop_table('order', schema='main')
    op.drop_index(op.f('ix_main_user_name'), table_name='user', schema='main')
    op.drop_index(op.f('ix_main_user_id'), table_name='user', schema='main')
    op.drop_table('user', schema='main')
    op.drop_index(op.f('ix_main_product_name'), table_name='product', schema='main')
    op.drop_index(op.f('ix_main_product_id'), table_name='product', schema='main')
    op.drop_table('product', schema='main')
    # ### end Alembic commands ###
    op.execute("drop schema main")
